### ISSUE TITLE
[Bug] Mine and Slash crash issue.

### ISSUE THREAD

**Issue by AzureDoom** [AzureZhen/wow_mc_weapon_mods#1]
```
[19:50:31] [Server thread/WARN] [FML]: Registry Item: Override did not have an associated owner object. Name: wowweapons:touch_of_chaos Value: mod.azure.wowweapons.items.mineandslash.MSStaff@44e2a5d
[19:50:31] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
        at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549) ~[ForgeRegistry.class:?]
        at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:596) ~[GameData.class:?]
        at net.minecraftforge.registries.GameData.freezeData(GameData.java:249) ~[GameData.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:219) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[19:50:31] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/kreezxil/work/bod/./crash-reports/crash-2019-09-01_19.50.31-server.txt
```

**Comment by AzureDoom** [comment]
Fixed with 3c5529f
