### ISSUE TITLE
1.14.4 loot_tables messed up

### ISSUE THREAD

**Issue by Ruchian** [AzureZhen/wow_mc_weapon_mods#3]
Your mod is doing something weird to the loot tables. 
Mineshafts, strongholds, endcities, rooms with a spawner, these chests are completely emptied. I expect its due to a loot table null pointer exception, but I can't be certain because twitch fails me to give details.

Minecraft version: 1.14.4
Forge version: forge-28.1.111
modpack, something custom send by a friend.
Evidence of this bug:
`[Client thread/ERROR]: Couldn't parse loot table minecraft:chests/abandoned_mineshaft
java.lang.RuntimeException: Attempted to add a duplicate pool to loot table: dothack_inject
	at net.minecraft.world.storage.loot.LootTable.addPool(LootTable.java:237) ~[?:?]
	at mod.azure.wowweapons.util.LootHandler.lootLoad(LootHandler.java:36) ~[?:0.1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_16_LootHandler_lootLoad_LootTableLoadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:629) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:831) ~[?:?]
	at net.minecraft.world.storage.loot.LootTableManager.lambda$apply$0(LootTableManager.java:47) [?:?]
	at net.minecraft.world.storage.loot.LootTableManager$$Lambda$5309/1700488119.accept(Unknown Source) [?:?]
	at java.util.HashMap.forEach(HashMap.java:1280) [?:1.8.0_51]
	at net.minecraft.world.storage.loot.LootTableManager.func_212853_a_(LootTableManager.java:44) [?:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_212853_a_(LootTableManager.java:24) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$3564/1852527981.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$4154/1030048250.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at jeresources.util.LootTableHelper.getManager(LootTableHelper.java:167) [?:0.10.0.70]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:42) [?:0.10.0.70]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:33) [?:0.10.0.70]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) [?:0.10.0.70]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) [?:0.10.0.70]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:71) [?:0.10.0.70]
	at mezz.jei.load.PluginLoader.lambda$new$2(PluginLoader.java:108) [?:6.0.0.27]
	at mezz.jei.load.PluginLoader$$Lambda$6314/1558590331.accept(Unknown Source) [?:6.0.0.27]
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) [?:6.0.0.27]
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:108) [?:6.0.0.27]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:71) [?:6.0.0.27]
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:127) [?:6.0.0.27]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:104) [?:6.0.0.27]
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$4476/549679499.accept(Unknown Source) [?:6.0.0.27]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$1993/1410901593.invoke(Unknown Source) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:1018) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1268) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:28) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$6234/1891947650.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.111.jar:28.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$409/1292325833.call(Unknown Source) [forge-1.14.4-28.1.111.jar:28.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]
[Client thread/ERROR]: Exception caught during firing event: Attempted to add a duplicate pool to loot table: dothack_inject
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class mod.azure.dothack.util.LootHandler lootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		2: ASM: class mod.azure.wowweapons.util.LootHandler lootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		3: ASM: class xxrexraptorxx.cdl.utils.Events lootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		4: ASM: class cursedflames.bountifulbaubles.common.loot.LootTableInjector onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		5: ASM: class vazkii.botania.common.core.loot.LootHandler lootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		6: ASM: vazkii.quark.tools.module.AncientTomesModule@4245f469 onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		7: ASM: de.teamlapen.vampirism.world.loot.LootHandler@6f587689 onLootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		8: ASM: vazkii.quark.vanity.module.ColorRunesModule@7f788089 onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		9: LOWEST
		10: ASM: class ovh.corail.tombstone.event.EventHandler onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
java.lang.RuntimeException: Attempted to add a duplicate pool to loot table: dothack_inject
	at net.minecraft.world.storage.loot.LootTable.addPool(LootTable.java:237)
	at mod.azure.wowweapons.util.LootHandler.lootLoad(LootHandler.java:36)
	at net.minecraftforge.eventbus.ASMEventHandler_16_LootHandler_lootLoad_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:629)
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:831)
	at net.minecraft.world.storage.loot.LootTableManager.lambda$apply$0(LootTableManager.java:47)
	at net.minecraft.world.storage.loot.LootTableManager$$Lambda$5309/1700488119.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraft.world.storage.loot.LootTableManager.func_212853_a_(LootTableManager.java:44)
	at net.minecraft.world.storage.loot.LootTableManager.func_212853_a_(LootTableManager.java:24)
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13)
	at net.minecraft.client.resources.ReloadListener$$Lambda$3564/1852527981.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader$$Lambda$4154/1030048250.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
	at jeresources.util.LootTableHelper.getManager(LootTableHelper.java:167)
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:42)
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:33)
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26)
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14)
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:71)
	at mezz.jei.load.PluginLoader.lambda$new$2(PluginLoader.java:108)
	at mezz.jei.load.PluginLoader$$Lambda$6314/1558590331.accept(Unknown Source)
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26)
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:108)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:71)
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:127)
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:104)
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$4476/549679499.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$1993/1410901593.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:1018)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1268)
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:28)
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15)
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
	at net.minecraft.network.PacketThreadUtil$$Lambda$6234/1891947650.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$409/1292325833.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)`
This repeats for a lot of locations.
Result: empty chests at various locations.

**Comment by AzureDoom** [comment]
fixed in build I'm releasing now. Please note that 1.14.4 is not ready until https://github.com/MinecraftForge/MinecraftForge/pull/6180 is merged. 1.15.1 already has this system and 1.14.4 should be receiving this shortly.
